<?php
$labels['label_title'] = 'Labels';
$labels['label_create'] = 'Label erstellen';
$labels['label_set'] = 'Label setzen';
$labels['label_matches'] = 'enthält';
$labels['label_color'] = 'Farbe';
$labels['label_delete'] = 'löschen';
$labels['label_name'] = 'Name';
$labels['label_folder'] = 'Suchen in ';
$labels['label_all'] = 'Alle Ordner';
$labels['label_pref'] = 'Labels verwalten';

$labels['deleteconfirm'] = 'Wollen Sie dieses Label wirklich löschen?';
$labels['add_row'] = 'hinzufügen';
$labels['delete_row'] = 'löschen';

$labels['headererror'] = 'Fehler in Suchregel für Nachrichten';
$labels['inputempty'] = 'Einer oder mehrere Suchergebnisse führen zu keinen Ergebnissen';
$labels['invalidcolor'] = 'Ungültige Farbe';

$labels['check_highlighting'] = 'Prüfe den Status für die Kennzeichnung von Nachrichten';
$labels['highlighting'] = 'Nachricht kennzeichnen';

$labels['check_labels'] = 'Prüfe Labels';
$labels['labels'] = 'Labels';

$labels['check_error'] = 'Fehler beim Überprüfen des Labels';

$labels['label_mode'] = 'Status anzeigen';
$labels['search_info'] = 'Suchinformationen';

$labels['display_label_on'] = 'Liste mit Labels anzeien';
$labels['display_label_off'] = 'Liste mit Labels nicht anzeigen';

?>